name = "OpenFuture"
license = "MIT"
licenselink = "https://bitbucket.org/pangenerator/open-future-www/src/master/LICENSE"
description = "Open Future one pager"
homepage = "http://openfuture.eu"
tags = []
features = []
min_version = "0.41.1"

[author]
    name = "panGenerator"
    homepage = "http://www.pangenerator.com"